project:
  type: website
  output-dir: docs

website:
  title: "Luessen Resume"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Resume
      - href: about.qmd
        text: Portfolio
    tools: 
      - icon: twitter
        href: https://twitter.com/LadyLuessen
      - icon: linkedin
        href: https://www.linkedin.com/in/michelle-luessen/ 

format:
  html:
    theme: 
      light: flatly
      dark: solar
    css: styles.css
    toc: true
  pdf: 
    documentclass: report
  docx: default
  pptx: default
      