project:
  type: website
  output-dir: docs

website:
  title: "Luessen Resume"
  navbar:
    left: 
      - href: index.qmd
        text: Resume
      - href: about.qmd
        text: Portfolio

format:
  html:
    theme: 
      light: flatly
      dark: solar
    css: styles.css
    toc: true
  pdf: 
    documentclass: report
  docx: default
  pptx: default
    



