---
title: "Michelle Luessen"
---

## Education

* University of Minnesota, Twin Cities (Degree in progress)
  * MS Science & Technical Communication 
* North Dakota State University, Graduation Date May 10, 2010
  * BS Psychology
  * Minor Neuroscience
  
## Work Experience

* Clinical Neurophysiology Technologist III
  * Mayo Clinic, 2019 - Present 
    * Prepare for and record EEGs, NCTs and ARSs
    * Explain procedures to patients
    * Monitor equipment and patient during recording

* Electroneurodiagnostic Techncian
  * Sanford Health, 2016 - 2019
    * Prepare for and record EEGs and NCTs
    * Explain procedures to patients
    * Monitor equipment and patient during recording

## Certifications

* Registered Electroencephalographic Technologist (R.EEG.T.)
  * American Board of Registration of Electroencephalographic and Evoked Potential Technologists (ABRET)
  * 01/02/2021 - 12/31/2026

* Certified Nerve Conduction Technologist (CNCT)
  * American Board of Electrodiagnostic Medicine (ABEM)
  * 06/07/2017 - 12/31/2027
  
## Research Experience

* Social Psychophysiology & Health Lab, NDSU
  * Research Lab Assistant
  * September 2007 - May 2010

* Personality, Perception & Affect Lab, NDSU
  * Research Lab Assistant
  * September 2008 - May 2010

* Vision, Attention & Multisensory Integration Lab, NDSU
  * Research Lab Assistant
  * January 2009 - May 2010

## Research Presentations

* Red River Psychology Conference 2010
  * Paper Presentation, Honors Thesis
  * Personality Traits and Opinion Modeling:  The effects of similarity and dissimilarity of novel stimuli on liking another person
  * Michelle Winings, Amber Koblitz, MS & Clayton J. Hilmert, PhD

* Red River Psychology Conference 2008
  * Poster Presentation
  * Attraction and Repulsion:  The effects of similarity and dissimilarity on liking another person
  * Michelle Winings, Andrea Rooney, BA & Clayton J. Hilmert, PhD

## Honors	

* Dr. Patricia Beatty Scholarship, NDSU
  * 2008 - 2010  
  * Departmental award for sophomore-level research contributions
* Marine Corps Scholarship Foundation
  * 2006 - 2010
  
## Academic Activities

* NDSU Psi Chi - Honor Society in Psychology
  * NDSU President
    * January 2010 - May 2010
  * NDSU Psi Chi Vice President
    * May 2008 - January 2010


* NDSU Psychology Club
  * September 2006 - May 2010


* NDSU Mortar Board Senior Honor Society
  * Director of Communications
    * September 2009 - May 2010

::: {.content-hidden when-format="pptx"}
* NDSU Golden Key Honour Society
  * Secretary
    * April 2008 - May 2010
:::

## Community Involvement 

* Epilepsy Foundation of Minnesota
  * Eastern MN Regional Board Member
    * January 2017 - May 2019
  * Southeast MN Regional Board Member
    * May 2019 - November 2022

* American Red Cross 
  * Online Course Reviewer
    * April 2018 - Present

::: {.content-hidden when-format="pptx"}
* Red River Community Emergency Response Team
  * General Volunteer
    * May 2018 - May 2019
:::


